name: TLDChatcolor
main: com.tldchatcolor.TLDChatcolorPlugin
version: 1.0.0
api-version: "1.21"
folia-supported: true
softdepend:
  - PlaceholderAPI
commands:
  chatcolor:
    description: Open the chat color menu
    usage: /chatcolor
permissions:
  tldchatcolor.use:
    description: Allows the player to open /chatcolor
    default: op
  tldchatcolor.reload:
    description: Allows reloading ChatColor configs
    default: op
